# Generated by Django 4.1.6 on 2023-02-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_news_options_alter_news_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(),
        ),
    ]
