# Generated by Django 4.0 on 2023-02-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text_de',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='text_fr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='title_de',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fr',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='text_de',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='page',
            name='text_fr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='page',
            name='title_de',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='title_fr',
            field=models.CharField(default='', max_length=50),
        ),
    ]
