# Generated by Django 4.0 on 2023-02-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_comment_app', '0002_rename_commentwithtitle_customizedcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedcomment',
            name='localization',
            field=models.CharField(choices=[('fr', 'Français'), ('de', 'Deutsch'), ('en', 'English')], default='en', max_length=10),
        ),
    ]
